### ISSUE TITLE
Cut guide is less reliable than a fold

### ISSUE THREAD

**Issue by xurizaemon** [brandoncorbin/corbinizer#1]
The "cut guide" on the 2015 edition may not be correctly positioned if the printer / paper aren't correctly aligned. On the A4 version at least, they are about 5mm out coming out of my printer.

On the previous template this was only noticeable as unbalanced margins, but with the cut guide it's quite noticeable - if you cut by the fold, there's a random line floating around on one side.

(I like the idea of the cut guide and I love the new design otherwise. This might be an A4 thing, or it might be a dodgy old printer thing my end. I have only a modified copy of the A4 template ... wish I'd preserved the previous A4 template so I could submit it for inclusion.)

EDIT: here 'tis. 
- http://jan.wildeboer.net/2014/01/paper-task-management-the-corbinizer-as-a4/
- http://jan.wildeboer.net/wp-content/uploads/2014/01/CorbinizerA4.pdf

**Comment by xurizaemon** [comment]
This is the pretty much ultimate trivia / whitespace issue submission don't you think?

**Comment by brandoncorbin** [comment]
I about sent you a message on the Twitter asking if you'd want to create the A4 version again... Hell I don't even own A4 paper - so it's possible it's the design.  I just pushed the updates without the cut mark.

**Comment by xurizaemon** [comment]
Ha, fair enough! Thanks.

**Comment by xurizaemon** [comment]
(are there design files if someone wanted to do such a thing?)

**Comment by brandoncorbin** [comment]
Absolutely! These are Illustrator PDFs - so they should be fully editable.
